// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYDPQBt5WJzrS2Ro3uMhAbGuITnFvIWQ',
    appId: '1:731212606018:web:f42fe5f5d0b70441b31bdb',
    messagingSenderId: '731212606018',
    projectId: 'alma-533d2',
    authDomain: 'alma-533d2.firebaseapp.com',
    storageBucket: 'alma-533d2.firebasestorage.app',
    measurementId: 'G-1WW5FLCEKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMa5N5TKV4X8-rNKCgSU4Zj1dcNhCoeCY',
    appId: '1:731212606018:android:5776f1ca5f64b203b31bdb',
    messagingSenderId: '731212606018',
    projectId: 'alma-533d2',
    storageBucket: 'alma-533d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkAOldo3RX8gR4QPcAVfsTueo_M54_eic',
    appId: '1:731212606018:ios:e1b9a103a3efb251b31bdb',
    messagingSenderId: '731212606018',
    projectId: 'alma-533d2',
    storageBucket: 'alma-533d2.firebasestorage.app',
    iosBundleId: 'com.alma.alma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWYDPQBt5WJzrS2Ro3uMhAbGuITnFvIWQ',
    appId: '1:731212606018:web:1b0fc03758bde9ddb31bdb',
    messagingSenderId: '731212606018',
    projectId: 'alma-533d2',
    authDomain: 'alma-533d2.firebaseapp.com',
    storageBucket: 'alma-533d2.firebasestorage.app',
    measurementId: 'G-FQ44798CNE',
  );
}
